export const GET_APPS_MY_REQUEST = "GET_APPS_MY_REQUEST";
export const GET_APPS_MY_SUCCESS = "GET_APPS_MY_SUCCESS";
export const GET_APPS_MY_FAIL = "GET_APPS_MY_FAIL";

export const GET_APPS_REQUEST = "GET_APPS_REQUEST";
export const GET_APPS_SUCCESS = "GET_APPS_SUCCESS";
export const GET_APPS_FAIL = "GET_APPS_FAIL";
