export const GET_TEMPLATES_REQUEST = "GET_TEMPLATES_REQUEST";
export const GET_TEMPLATES_SUCCESS = "GET_TEMPLATES_SUCCESS";
export const GET_TEMPLATES_FAIL = "GET_TEMPLATES_FAIL";

export const NEW_TEMPLATE_REQUEST = "NEW_TEMPLATE_REQUEST";
export const NEW_TEMPLATE_SUCCESS = "NEW_TEMPLATE_SUCCESS";
export const NEW_TEMPLATE_FAIL = "NEW_TEMPLATE_FAIL";
